### PR TITLE
Timeline layout changed other css fixed

### PR DESCRIPTION
**Pull request by maheshn22**

### CODE REVIEW

**Comment by sanket9006** [comment]
Capture
Hey please do the necessary changes for the mobile view as well

**Comment by aravindvnair99** [comment]
@maheshn22 Moving this to draft for the time being until the bug is fixed.

**Comment by sanket9006** [comment]
actually, the PR is outdated! Just got implemented react-router so please make another one, but before that do pull the latest copy this repo

**Comment by maheshn22** [comment]
Ohh okay, I'm fixing the mobile view and will make a new PR with the latest copy of repo

**Pull request closed without merging**
